spring:
  profiles:
    active: dev # 开发环境
  application:
    name: userMS-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/haiy?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  # session 失效时间
  session:
    timeout: 1800 # session过期时间，单位为秒，默认30分钟
  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.userms.usermsbackend.controller    #这里换成你模块下controller包的路径

# knife4j的增强配置，不需要增强可以不配（建议配置一下）
knife4j:
  enable: true
  setting:
    language: zh_cn